apiVersion: v1
kind: ConfigMap
metadata:
  name: invoice-to-pdf-service-config
  namespace: rac-app
data:
  INVOICE_SERVICE_URL: "http://invoice-service:8000"
  COMPANY_SERVICE_GRPC_TARGET: "company-service:50051"
  PARTNER_SERVICE_GRPC_TARGET: "partner-service:50051"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-to-pdf-service
  namespace: rac-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-to-pdf-service
  template:
    metadata:
      labels:
        app: invoice-to-pdf-service
    spec:
      containers:
        - name: invoice-to-pdf-service
          image: invoice-to-pdf-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: invoice-to-pdf-service-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: invoice-to-pdf-service
  namespace: rac-app
spec:
  selector:
    app: invoice-to-pdf-service
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
