apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors-plugin
  namespace: rac-app
  annotations:
    kubernetes.io/ingress.class: kong
plugin: cors
config:
  origins:
    - http://localhost:3000
  credentials: true
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
